---
# Nginx

- name: install Nginx
  yum: pkg={{ item }} state=installed
  with_items:
    - nginx

- name: Delete nginx/conf.d/default.conf
  file: path=/etc/nginx/conf.d/default.conf state=absent

- name: ensure nginx is running automatically at boot time
  service: name=nginx state=started enabled=yes

