---
# Nginx

- name: install Nginx
  yum: pkg={{ item }} state=installed
  with_items:
    - nginx

- name: Delete nginx/conf.d/default.conf
  file: path=/etc/nginx/conf.d/* state=absent

- name: ensure nginx is running automatically at boot time
  service: name=nginx state=started enabled=yes

- name: deploy certificate
  copy: src=nginx.crt dest=/etc/nginx/conf.d/nginx.crt owner=root group=root mode=0644

- name: deploy certificate key
  copy: src=nginx.key dest=/etc/nginx/conf.d/nginx.key owner=root group=root mode=0644

