- name: Setup Cluster Server1
  hosts: server1
  sudo: true
  user: vagrant
  roles:
    - lvm
    - drbd
    - pacemaker

- name: Setup Cluster Server2
  hosts: server2
  sudo: true
  user: vagrant
  roles:
    - lvm
    - drbd
    - pacemaker

