---
- name: download kibana archive
  get_url: >
    url={{ kibana_configs.dl_url }}
    dest={{ kibana_configs.archive_path }}

- name: unarchive
  unarchive: >
    src={{ kibana_configs.archive_path }}
    dest={{ kibana_configs.install_path }}
    creates={{ kibana_configs.install_path }}/{{ kibana_configs.install_name }}
    copy=no

- name: create symbolic link
  file: >
    src={{ kibana_configs.install_path }}/{{ kibana_configs.install_name }}
    dest={{kibana_configs.install_path }}/kibana
    state=link

- name: copy init script
  copy: >
    src=kibana
    dest=/etc/init.d/kibana
    mode=755

- name: service start & enabled
  service: name=kibana state=started enabled=yes
