---
# jenkins

- name: include variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: install packages
  include: package-RedHat.yml
  when: "ansible_os_family == 'RedHat'"

- name: install packages
  include: package-Debian.yml
  when: "ansible_os_family == 'Debian'"

- name: ensure jenkins is running and enabled
  service: name=jenkins state=started enabled=yes

- name: setting
  include: setting.yml

# - pause: minutes=1

- name: Get the jenkins-cli jarfile from the Jenkins server.
  get_url:
    url: "http://{{ jenkins_hostname }}:{{ jenkins_http_port }}{{ jenkins_url_prefix }}/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_jar_location }}"
  register: jarfile_get
  until: "'OK' in jarfile_get.msg or 'file already exists' in jarfile_get.msg"
  retries: 5
  delay: 10
  check_mode: no


- name: Remove Jenkins security init scripts after first startup.
  file:
    path: "{{ jenkins_home }}/init.groovy.d/init-security.groovy"
    state: absent

- name: install plugins
  include: plugins.yml

- name: restart nginx
  service: name=nginx state=restarted
