---
# setup package for RedHat

  - name: ensure open JDK 1.7 is at the latest version
    yum: name=java-1.7.0-openjdk state=latest

  - name: get the Jenkins repository
    get_url: url=http://pkg.jenkins-ci.org/redhat/jenkins.repo dest=/etc/yum.repos.d/jenkins.repo

  - name: add the Jenkins repository
    rpm_key: key=https://jenkins-ci.org/redhat/jenkins-ci.org.key

  - name: ensure jenkins is at the latest version
    yum: name=jenkins state=latest
