# -*- mode: ruby -*-
# vi: set ft=ruby :

require 'yaml'

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  if ENV['USE_PROXY']
    proxy = YAML.load_file("#{Dir.home}/.vagrant.d/proxy.yaml")
    config.proxy.http    = proxy["proxy"]["http"]
    config.proxy.https   = proxy["proxy"]["https"]
    config.proxy.no_proxy = proxy["proxy"]["no_proxy"]
  end

  config.vm.define "gitlab"
  config.vm.box = "centos-6.6-x86_64"
  config.vm.hostname = "gitlab-on-centos"
  config.vm.synced_folder "./share", "/vagrant", mount_options: ["dmode=755", "fmode=755"]
  config.vm.network :private_network, ip:"192.168.56.15"

  config.vm.provider :virtualbox do |v, override|
    v.customize ["modifyvm", :id, "--memory", 2 * 1024]
    v.customize ["modifyvm", :id, "--cpus", "2"]
  end

  $script = <<-SCRIPT
    yum -y update
    sed -i 's/^/#/g' /etc/sysconfig/i18n
    echo 'LANG="ja_JP.utf8"' >> /etc/sysconfig/i18n
		curl -L http://ftp.riken.jp/Linux/fedora/epel/6/i386/epel-release-6-8.noarch.rpm -o epel-release-6-8.noarch.rpm
		rpm -ivh epel-release-6-8.noarch.rpm
		rm epel-release-6-8.noarch.rpm
		yum -y groupinstall "development tools"
		yum -y --enablerepo=epel install zlib-devel openssl-devel gdbm-devel readline-devel ncurses-devel libffi-devel libxml2-devel libxslt-devel libcurl-devel libicu-devel libyaml-devel expect expat-devel redis python-docutils
		yum install -y perl-ExtUtils-MakeMaker
		yum erase -y git
		curl --progress https://www.kernel.org/pub/software/scm/git/git-2.0.0.tar.gz | tar xz
		cd git-2.0.0
		make prefix=/usr/local all | tee make.log
		make prefix=/usr/local install
		rm -rf git-2.0.0
		useradd git
		chmod 755 /home/git
    sudo -H -u git -i /usr/local/bin/git clone https://github.com/sstephenson/rbenv.git /home/git/.rbenv
		sudo -H -u git -i sh -c "echo 'export PATH=\\$HOME/.rbenv/bin:\\$PATH' >> /home/git/.bash_profile"
    sudo -H -u git -i sh -c "echo 'eval \\"\\$(rbenv init -)\\"' >> /home/git/.bash_profile"
    sudo -H -u git -i /usr/local/bin/git clone https://github.com/sstephenson/ruby-build.git /home/git/.rbenv/plugins/ruby-build
    sudo -H -u git -i rbenv install 2.1.2
		sudo -H -u git -i rbenv global 2.1.2
    yum install -y http://yum.postgresql.org/9.3/redhat/rhel-6-x86_64/pgdg-centos93-9.3-1.noarch.rpm
    yum install -y postgresql93-server postgresql93 postgresql93-libs postgresql93-contrib postgresql93-devel
    sudo -H -u postgres -i /usr/pgsql-9.3/bin/initdb /var/lib/pgsql/9.3/data
    chkconfig postgresql-9.3 on
    /etc/init.d/postgresql-9.3 start
    sudo -H -u postgres -i psql -d template1 -c 'CREATE USER git CREATEDB;'
    sudo -H -u postgres -i psql -d template1 -c 'CREATE DATABASE gitlabhq_production OWNER git;'

    sudo -H -u git -i /usr/local/bin/git clone https://gitlab.com/gitlab-org/gitlab-ce.git -b 7-0-stable gitlab
    sudo -H -u git -i sh -c "cp ~/gitlab/config/gitlab.yml.example ~/gitlab/config/gitlab.yml"
    sudo -H -u git -i sh -c "sed -ri 's/host: localhost/host: 192.168.56.10/g' ~/gitlab/config/gitlab.yml"
    sudo -H -u git -i sh -c "sed -ri 's/# relative_url_root/relative_url_root/g' ~/gitlab/config/gitlab.yml"
    sudo -H -u git -i sh -c "chmod -R u+rwX ~/gitlab/log/"
    sudo -H -u git -i sh -c "chmod -R u+rwX ~/gitlab/tmp/"
    sudo -H -u git -i sh -c "mkdir /home/git/gitlab-satellites"
    sudo -H -u git -i sh -c "chmod u+rwx,g=rx,o-rwx /home/git/gitlab-satellites"
    sudo -H -u git -i sh -c "chmod -R u+rwX ~/gitlab/tmp/pids/"
    sudo -H -u git -i sh -c "chmod -R u+rwX ~/gitlab/tmp/sockets/"
    sudo -H -u git -i sh -c "chmod -R u+rwX  ~/gitlab/public/uploads"
    sudo -H -u git -i sh -c "cp ~/gitlab/config/unicorn.rb.example ~/gitlab/config/unicorn.rb"
    sudo -H -u git -i sh -c "sed -ri 's/worker_processes 2/worker_processes 15/g' ~/gitlab/config/unicorn.rb"
    sudo -H -u git -i sh -c "sed -ri 's/# ENV/ENV/g' ~/gitlab/config/unicorn.rb"
    sudo -H -u git -i sh -c "cp ~/gitlab/config/initializers/rack_attack.rb.example ~/gitlab/config/initializers/rack_attack.rb"
    sudo -H -u git -i sh -c "/usr/local/bin/git config --global user.name \"GitLab\""
    sudo -H -u git -i sh -c "/usr/local/bin/git config --global user.email \"example@example.com\""
    sudo -H -u git -i sh -c "/usr/local/bin/git config --global core.autocrlf input"
    sudo -H -u git -i sh -c "cp ~/gitlab/config/database.yml.postgresql ~/gitlab/config/database.yml"
    sudo -H -u git -i sh -c "chmod o-rwx ~/gitlab/config/database.yml"
#    sudo -H -u git -i sh -c "echo \"http_proxy: http://xxxx:xxxx@xxxx.co.jp:8080\" >> ~/.gemrc"
#    sudo -H -u git -i sh -c "echo \"https_proxy: http://xxxx:xxxx@xxxx.co.jp:8080\" >> ~/.gemrc"
    sudo -H -u git -i sh -c "gem install bundle"
    sudo -H -u git -i sh -c "cd ~/gitlab;bundle config build.pg --with-pg-config=/usr/pgsql-9.3/bin/pg_config --with-pg-include=/usr/pgsql-9.3/include/;bundle install --deployment --without development test mysql aws"

    sudo -H -u git -i sh -c 'echo "export PATH=/usr/local/bin:\$PATH" >> ~/.bashrc'
    chkconfig redis on
    /etc/init.d/redis start
    sudo -H -u git -i sh -c "cd ~/gitlab;bundle exec rake gitlab:shell:install[v1.9.6] REDIS_URL=redis://localhost:6379 RAILS_ENV=production"

    echo "yes" | sudo -H -u git -i sh -c "cd ~/gitlab;bundle exec rake gitlab:setup RAILS_ENV=production"

    cp /home/git/gitlab/lib/support/init.d/gitlab /etc/init.d/gitlab
    cp /home/git/gitlab/lib/support/init.d/gitlab.default.example /etc/default/gitlab

    cp /home/git/gitlab/lib/support/logrotate/gitlab /etc/logrotate.d/gitlab

    sudo -H -u git -i sh -c "cd ~/gitlab;bundle exec rake assets:precompile RAILS_ENV=production"

    /etc/init.d/gitlab start

    rpm -ivh http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm
    yum install -y nginx
    sudo -H -u git -i sh -c "sed -ri 's/# config.relative_url_root/config.relative_url_root/g' ~/gitlab/config/application.rb"
    #mkdir -p /etc/nginx/sites-available
    #mkdir -p /etc/nginx/sites-enabled
    #cp /home/git/gitlab/lib/support/nginx/gitlab /etc/nginx/sites-available/gitlab
    #ln -s /etc/nginx/sites-available/gitlab /etc/nginx/sites-enabled/gitlab
    mv /etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf.bk
    cp /home/git/gitlab/lib/support/nginx/gitlab /etc/nginx/conf.d/gitlab.conf
    chkconfig nginx on
    /etc/init.d/nginx start

    sed -ri 's/-A INPUT -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT/-A INPUT -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT\\n-A INPUT -m state --state NEW -m tcp -p tcp --dport 80 -j ACCEPT/g' /etc/sysconfig/iptables
    sudo sh -c "iptables-restore < /etc/sysconfig/iptables"

    yum clean all
  SCRIPT

  config.vm.provision :shell do |s|
    s.inline = $script
  end

end
