# -*- mode: ruby -*-
# vi: set ft=ruby :

Dotenv.load
ENV['VAGRANT_DEFAULT_PROVIDER'] = "aws"

require 'yaml'

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  aws_ssh_username = ENV['AWS_SSH_USERNAME']
  aws_ssh_key = ENV['AWS_SSH_KEY']
  aws_access_key_id = ENV['AWS_ACCESS_KEY_ID']
  aws_secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']
  aws_keypair_name = ENV['AWS_KEYPAIR_NAME']
  aws_security_group = ENV['AWS_SECURITY_GROUP']
  aws_subnet_id= ENV['AWS_SUBNET_ID']
  aws_ami_id= ENV['AWS_AMI_ID']
  user_data= ENV['USER_DATA']

  config.vm.box = "dummy"
  config.vm.box_url = "https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box"
  config.vm.synced_folder "./provisioning", "/vagrant", mount_options: ["dmode=755", "fmode=755"]

  config.vm.define :server1 do |server1|
    server1.vm.provider "aws" do |aws, override|
      aws.ami = aws_ami_id
      aws.tags = {
        'Name' => 'test',
      }
      aws.subnet_id = aws_subnet_id
      aws.private_ip_address = '172.31.0.200'
      aws.elastic_ip = true
      aws.associate_public_ip = true
      aws.instance_type = "t2.micro"
      aws.security_groups = aws_security_group
      aws.access_key_id = aws_access_key_id
      aws.secret_access_key = aws_secret_access_key
      aws.region = "ap-northeast-1"
      aws.keypair_name = aws_keypair_name
      aws.user_data = user_data

      override.ssh.username = aws_ssh_username
      override.ssh.private_key_path = aws_ssh_key
    end
    server1.vm.provision "ansible" do |ansible|
      ansible.playbook = "provisioning/site.yml"
    end
    server1.vm.provision :serverspec do |spec|
      spec.pattern = "spec/server1/*_spec.rb"
    end
  end
end
